# Generated by Django 4.1.7 on 2023-03-06 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=25)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_start", models.CharField(max_length=4)),
                ("season_end", models.CharField(max_length=4)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сезон",
                "verbose_name_plural": "Сезоны",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=25)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DF", "Defender"),
                            ("MD", "Midfielder"),
                            ("FW", "Forward"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.season"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tour",
                    models.IntegerField(
                        choices=[
                            [1, 1],
                            [2, 2],
                            [3, 3],
                            [4, 4],
                            [5, 5],
                            [6, 6],
                            [7, 7],
                            [8, 8],
                            [9, 9],
                            [10, 10],
                            [11, 11],
                            [12, 12],
                            [13, 13],
                            [14, 14],
                            [15, 15],
                            [16, 16],
                            [17, 17],
                            [18, 18],
                            [19, 19],
                            [20, 20],
                            [21, 21],
                            [22, 22],
                            [23, 23],
                            [24, 24],
                            [25, 25],
                            [26, 26],
                            [27, 27],
                            [28, 28],
                            [29, 29],
                            [30, 30],
                            [31, 31],
                            [32, 32],
                            [33, 33],
                            [34, 34],
                            [35, 35],
                            [36, 36],
                            [37, 37],
                            [38, 38],
                        ]
                    ),
                ),
                ("note", models.TextField()),
                ("substatution_on", models.CharField(max_length=25)),
                (
                    "screenshot",
                    models.ImageField(blank=True, upload_to="photos_of_notes/%Y/%m/%d"),
                ),
                ("slug", models.SlugField(max_length=25, unique=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.team"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.season"
                    ),
                ),
                (
                    "substatution_off",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.player"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметки",
            },
        ),
    ]
