name: notes_action
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: tests
        uses: actions/checkout@v3
      - name: poetry
        run: poetry install
      - name: black
        run: black .




