name: notes_action
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
